* long working on busybox 1.17.2 to make it work * deep reworking on the start scripts, many sanity checks now implemented * moving /etc/nsswitch and /etc/host.conf to /var/etc * soem little changes to fstab.in and inittab
git-svn-id: http://www.openmct.org/svn/trunk@640 052c2572-4cfa-0310-8799-9599af202008

diff --git a/openmct/packages/build/buildetc/new/etc/init.d/S02recovery b/openmct/packages/build/buildetc/new/etc/init.d/S02recovery
--- a/openmct/packages/build/buildetc/new/etc/init.d/S02recovery
+++ b/openmct/packages/build/buildetc/new/etc/init.d/S02recovery
@@ -1,7 +1,13 @@
 #!/bin/sh
 
+/bin/echo -e "\n[\033[1;34m$0\033[0m]"
+
 # loading recovery kernel modul
-/sbin/modprobe recovery
+if /sbin/modprobe recovery ; then
+    /bin/echo -e "Loading kernel modul \"recovery\" \033[1;32msuccessfully\033[0m."
+else
+    /bin/echo -e "Loading kernel modul \"recovery\" \033[1;31mfailed!\033[0m"
+fi
 
 RECOVER_REQUEST=/var/.recover
 
@@ -19,21 +25,21 @@ fi
 }
 
 case "$1" in
-	start)
-	    /bin/echo -n "Checking for recover something ... "
-	    recover_network
-	    ;;
+    start)
+	/bin/echo -n "Checking for recover something ... "
+	recover_network
+	;;
 
-        force)
-	    /bin/touch $RECOVER_REQUEST
-            $0 start
-	    reboot
-            ;;
+    force)
+	/bin/touch $RECOVER_REQUEST
+	$0 start
+	reboot
+	;;
 
-        *)
-            echo "Usage: $0 {start|force} #force is for recover without reset button!"
-            exit 1
-    	    ;;
+    *)
+	/bin/echo "Usage: $0 {start|force} #force is for recover without reset button!"
+	exit 1
+	;;
 esac
 # extract var.tar.gz in case that's neccessary
 
@@ -45,4 +51,6 @@ esac
 #fi
 #echo "done."
 
+#/bin/echo -e "[\033[7;34mfinished.\033[0m]"
+/bin/echo -e "[finished]"
 exit 0
